// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameArticleM = "article_models"

// ArticleM mapped from table <article_models>
type ArticleM struct {
	ID          int64          `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id"`
	Slug        string         `gorm:"column:slug;type:varchar(255);not null;uniqueIndex:idx_article_models_slug" json:"slug"`
	Title       string         `gorm:"column:title;type:varchar(255);not null" json:"title"`
	Description *string        `gorm:"column:description;type:text" json:"description"`
	Body        *string        `gorm:"column:body;type:text" json:"body"`
	AuthorID    int64          `gorm:"column:author_id;type:bigint(20) unsigned;not null;index:idx_article_models_author_id,priority:1" json:"author_id"`
	CreatedAt   *time.Time     `gorm:"column:created_at;type:timestamp;default:current_timestamp()" json:"created_at"`
	UpdatedAt   *time.Time     `gorm:"column:updated_at;type:timestamp;default:current_timestamp()" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp" json:"deleted_at"`
}

// TableName ArticleM's table name
func (*ArticleM) TableName() string {
	return TableNameArticleM
}
