// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameArticleTagM = "article_tags"

// ArticleTagM mapped from table <article_tags>
type ArticleTagM struct {
	ArticleModelID int64 `gorm:"column:article_model_id;type:bigint(20) unsigned;primaryKey" json:"article_model_id"`
	TagModelID     int64 `gorm:"column:tag_model_id;type:bigint(20) unsigned;primaryKey;index:tag_model_id,priority:1" json:"tag_model_id"`
}

// TableName ArticleTagM's table name
func (*ArticleTagM) TableName() string {
	return TableNameArticleTagM
}
