// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCommentM = "comment_models"

// CommentM mapped from table <comment_models>
type CommentM struct {
	ID        int64          `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id"`
	ArticleID int64          `gorm:"column:article_id;type:bigint(20) unsigned;not null;index:idx_comment_models_article_id,priority:1" json:"article_id"`
	AuthorID  int64          `gorm:"column:author_id;type:bigint(20) unsigned;not null;index:idx_comment_models_author_id,priority:1" json:"author_id"`
	Body      string         `gorm:"column:body;type:text;not null" json:"body"`
	CreatedAt *time.Time     `gorm:"column:created_at;type:timestamp;default:current_timestamp()" json:"created_at"`
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:timestamp;default:current_timestamp()" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp" json:"deleted_at"`
}

// TableName CommentM's table name
func (*CommentM) TableName() string {
	return TableNameCommentM
}
