// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameFavoriteM = "favorite_models"

// FavoriteM mapped from table <favorite_models>
type FavoriteM struct {
	ID           int64          `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id"`
	FavoriteID   int64          `gorm:"column:favorite_id;type:bigint(20) unsigned;not null;uniqueIndex:unique_favorite,priority:1" json:"favorite_id"`
	FavoriteByID int64          `gorm:"column:favorite_by_id;type:bigint(20) unsigned;not null;uniqueIndex:unique_favorite,priority:2;index:idx_favorite_models_favorite_by_id,priority:1" json:"favorite_by_id"`
	CreatedAt    *time.Time     `gorm:"column:created_at;type:timestamp;default:current_timestamp()" json:"created_at"`
	UpdatedAt    *time.Time     `gorm:"column:updated_at;type:timestamp;default:current_timestamp()" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp" json:"deleted_at"`
}

// TableName FavoriteM's table name
func (*FavoriteM) TableName() string {
	return TableNameFavoriteM
}
