// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameFollowM = "follow_models"

// FollowM mapped from table <follow_models>
type FollowM struct {
	ID           int64          `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id"`
	FollowingID  int64          `gorm:"column:following_id;type:bigint(20) unsigned;not null;uniqueIndex:unique_follow,priority:1" json:"following_id"`
	FollowedByID int64          `gorm:"column:followed_by_id;type:bigint(20) unsigned;not null;uniqueIndex:unique_follow,priority:2;index:idx_follow_models_followed_by_id,priority:1" json:"followed_by_id"`
	CreatedAt    *time.Time     `gorm:"column:created_at;type:timestamp;default:current_timestamp()" json:"created_at"`
	UpdatedAt    *time.Time     `gorm:"column:updated_at;type:timestamp;default:current_timestamp()" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp" json:"deleted_at"`
}

// TableName FollowM's table name
func (*FollowM) TableName() string {
	return TableNameFollowM
}
