// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTagM = "tag_models"

// TagM mapped from table <tag_models>
type TagM struct {
	ID        int64          `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id"`
	Tag       string         `gorm:"column:tag;type:varchar(255);not null;uniqueIndex:idx_tag_models_tag" json:"tag"`
	CreatedAt *time.Time     `gorm:"column:created_at;type:timestamp;default:current_timestamp()" json:"created_at"`
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:timestamp;default:current_timestamp()" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp" json:"deleted_at"`
}

// TableName TagM's table name
func (*TagM) TableName() string {
	return TableNameTagM
}
