// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserM = "user_models"

// UserM mapped from table <user_models>
type UserM struct {
	ID        int64          `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id"`
	Username  string         `gorm:"column:username;type:varchar(255);not null;uniqueIndex:idx_user_models_username" json:"username"`
	Email     string         `gorm:"column:email;type:varchar(255);not null;uniqueIndex:idx_user_models_email" json:"email"`
	Bio       *string        `gorm:"column:bio;type:text" json:"bio"`
	Image     *string        `gorm:"column:image;type:varchar(255)" json:"image"`
	Password  string         `gorm:"column:password;type:varchar(255);not null" json:"password"`
	CreatedAt *time.Time     `gorm:"column:created_at;type:timestamp;default:current_timestamp()" json:"created_at"`
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:timestamp;default:current_timestamp()" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;index:idx_user_models_deleted_at,priority:1" json:"deleted_at"`
}

// TableName UserM's table name
func (*UserM) TableName() string {
	return TableNameUserM
}
